version: '3.7'
services:
  sierra-reports:
    build: .
    container_name: sierra-reports
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/
    command: npm start
    restart: always